name: Deploy React to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Generate version files
        run: |
          node scripts/generate-sw-version.js

      - name: Install dependencies
        run: npm ci

      - name: Build React App
        run: npm run build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete --exclude "uploads/*"
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2
          SOURCE_DIR: build

      - name: Clean up old service worker versions
        run: |
          cd public
          ls -1t service-worker.*.js | grep -v 'template.js' | tail -n +2 | xargs -r rm --
